# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3094c7f638862cdff22540a46f8e37457f67ba5a742db9b63e2f74d78b4e2d79ea1b24c93af13e9f4c450b3119696a0a7fa2c12ea7e4f4d30e2226bbd1349c94

test:
  secret_key_base: 2a5a5120197edb8397fd508d225a4a1f8b2d0c0cc51988212ce0abac802da115cdf351f1f1de84e0349dc378878bd4b23ac71d6b857fb1e0316c84ed41b1403f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
